# Generated by Django 4.2.1 on 2023-06-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recan_gui', '0002_rename_file_name_sessiondata_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondata',
            name='align_len',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='alignment_with_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='pot_rec_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='pot_rec_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='region_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='region_start',
            field=models.IntegerField(default=0),
        ),
    ]
