# Generated by Django 4.2.1 on 2023-06-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recan_gui', '0003_sessiondata_align_len_sessiondata_alignment_with_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondata',
            name='plot_div',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='window_shift',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='window_size',
            field=models.IntegerField(default=100),
        ),
    ]
