# Generated by Django 4.2.1 on 2023-06-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recan_gui', '0004_sessiondata_plot_div_sessiondata_window_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondata',
            name='window_shift',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='sessiondata',
            name='window_size',
            field=models.IntegerField(default=50),
        ),
    ]
