# Generated by Django 4.2.1 on 2023-06-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recan_gui', '0005_alter_sessiondata_window_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondata',
            name='dist_method',
            field=models.CharField(default='pdist', max_length=5),
        ),
    ]
