# Generated by Django 4.2 on 2023-11-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recan_gui', '0008_alter_sessiondata_alignment_with_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondata',
            name='align_file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
