# Generated by Django 4.2 on 2026-02-26 07:00

import app_recan_gui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recan_gui', '0009_sessiondata_align_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiondata',
            options={'verbose_name': 'Uploaded alignment and its plotting settings', 'verbose_name_plural': 'Uploaded alignments and their plotting settings'},
        ),
        migrations.AlterField(
            model_name='sessiondata',
            name='align_file',
            field=models.FileField(default=None, null=True, upload_to=app_recan_gui.models.save_file),
        ),
        migrations.AlterField(
            model_name='sessiondata',
            name='align_len',
            field=models.IntegerField(blank=True, null=True, verbose_name='sequence length'),
        ),
        migrations.AlterField(
            model_name='sessiondata',
            name='alignment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='alignment name'),
        ),
        migrations.AlterField(
            model_name='sessiondata',
            name='dist_method',
            field=models.CharField(default='pdist', max_length=5, verbose_name='genetic distance method'),
        ),
    ]
