# Generated by Django 4.2 on 2026-06-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recan_gui', '0010_alter_sessiondata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondata',
            name='legend_div',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
