# Generated by Django 4.2 on 2026-06-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_recan_gui', '0011_sessiondata_legend_div'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiondata',
            name='alignment_with_key',
        ),
    ]
